- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /tmp/docker.gpg

- name: Convert Docker GPG key
  ansible.builtin.shell:
    creates: /etc/apt/trusted.gpg.d/docker.gpg
    cmd: "gpg --no-default-keyring --keyring /tmp/temp-keyring.gpg --import /tmp/docker.gpg && gpg --no-default-keyring --keyring /tmp/temp-keyring.gpg --export --output /etc/apt/trusted.gpg.d/docker.gpg"

- name: Add Docker repo
  ansible.builtin.copy:
    content: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    dest: /etc/apt/sources.list.d/docker.list

- name: apt cache docker-ce
  ansible.builtin.shell:
    cmd: apt-cache policy docker-ce

- name: Install Docker package
  ansible.builtin.apt:
    update_cache: yes
    name: docker-ce
    state: present
